# -*- coding: utf-8 -*-
"""ann for student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9e6huLG1bhVl3fvQy-UqPEf7EKiieaE
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import tensorflow as tf

# =========================
# =========================
# 1. LOAD DATASET
# =========================
df = pd.read_csv("student_performance_interactions (1).csv")

# Drop ID if exists
if "student_id" in df.columns:
    df = df.drop(["student_id"], axis=1)

# =========================
# 2. SPLIT FEATURES & TARGET
# =========================
y = df["grade"]
X = df.drop("grade", axis=1)

# =========================
# 3. HANDLE CATEGORICAL DATA
# =========================
# Convert categorical columns → numerical
X = pd.get_dummies(X, drop_first=True)

# Encode target
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

# =========================
# 3. TRAIN-TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# =========================
# 4. FEATURE SCALING
# =========================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# =========================
# 5. BUILD NEURAL NETWORK
# =========================
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(5, activation='softmax')
])

# Compile
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# =========================
# 6. TRAIN MODEL
# =========================
model.fit(X_train, y_train, epochs=50, batch_size=16, verbose=1)

# =========================
# 7. EVALUATION
# =========================
y_pred = np.argmax(model.predict(X_test), axis=1)

print("\n✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred))
print("\n📌 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# =========================
# 8. SAMPLE PREDICTION
# =========================
# =========================
# SAMPLE INPUT (original format)
# =========================
sample = {
    "previous_score": 75,
    "motivation_score": 8,
    "daily_study_hours": 3,
    "exam_anxiety_score": 4,
    "homework_completion_rate": 80,
    "attendance_percentage": 85,
    "screen_time_hours": 2,
    "sleep_hours": 7,
    "parent_education_level": "Master"
}

# Convert to DataFrame
sample_df = pd.DataFrame([sample])

# Apply same encoding
sample_df = pd.get_dummies(sample_df)

# 🔥 MOST IMPORTANT LINE
sample_df = sample_df.reindex(columns=X.columns, fill_value=0)

# Scale
sample_scaled = scaler.transform(sample_df)

# Predict
prediction = model.predict(sample_scaled)
predicted_class = np.argmax(prediction, axis=1)

# Convert back
predicted_grade = le.inverse_transform(predicted_class)

print("🎯 Predicted Grade:", predicted_grade[0])

# =========================
# 9. RISK DETECTION
# =========================
if predicted_grade[0] in ['D', 'F']:
    print("⚠️ Student is AT RISK!")
else:
    print("✅ Student is performing well")